spring.application.name=quotes
spring.data.mongodb.database=quotes
spring.data.mongodb.uri=mongodb://localhost:27017/quotes
spring.data.mongodb.auto-index-creation=true

jwt.secret=Y2hhbmdlLXRoaXMtc2VjcmV0LWJlZm9yZS1nb2luZy10by1wcm9kdWN0aW9uIQ==
jwt.expiration-ms=86400000
